CREATE TABLE IF NOT EXISTS PORDERS(
    ORDER_ID INTEGER NOT NULL,
    CUST_ID INTEGER NOT NULL,
    ORDER_DATE DATE,
    AMOUNT DECIMAL,
    QUANTITY INTEGER CONSTRAINT PK PRIMARY KEY (ORDER_ID,CUST_ID)
)